CC:=gcc

app: main.o io.o deque.o sorting.o timer.o
	$(CC) main.o io.o deck.o -o app

main.o: main.c main.h
	$(CC) -c main.c

io.o: io.c io.h
	$(CC) -c io.c

deck.o: deque.c deque.h
	$(CC) -c deque.c

sorting.o: sorting.c sorting.h
	$(CC) -c sorting.c

timer.o: timer.c timer.h
	$(CC) -c timer.c

.PHONY: clear

clear:
	rm app
	rm *.o
	rm *.out